---
- name: Deploy Kubernetes resources to EKS
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Update kubeconfig for EKS cluster
      shell: |
        eksctl utils write-kubeconfig --cluster edureka-proj

#    - name: Delete existing deployments
#      shell: kubectl delete deployment edureka-proj-webapp
#
#    - name: Delete existing services
#      shell: kubectl delete service edureka-proj-webapp-service

    - name: Apply Kubernetes Deployment
      shell: kubectl apply -f k8s/deployment.yaml --validate=false

    - name: Force rollout of Deployment
      shell: kubectl rollout restart deployment edureka-proj-webapp

    - name: Apply Kubernetes Service
      shell: kubectl apply -f k8s/service.yaml --validate=false